config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get "cities/update", to: "cities#update"
  post "cities/update", to: "cities#post_up"
  resources :cities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City
	attr_accessor :name, :landmark, :population, :weather
	$cities = {}
	
	def initialize(city_params)
		@w = WeatherService.get(city_params[:name])
		if @w
    		@weather = (9.0/5) * (@w[:temperature] - 273)+ 32
    	else
    		@weather = 0
    	end
		@name = city_params[:name]
		@landmark = city_params[:landmark]
		@population = city_params[:population]
		#@weather = @temperature
	end

	def save
		$cities[@name.to_sym] = self
		
	end

	def self.all
    	$cities
  	end

	def update(update_params)
		# Your code here, for Task 4
		# Use update_params (a hash) to update the model
		self.landmark = update_params[:landmark]
		self.population = update_params[:population]
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
require_relative '../services/weather_service'

class CitiesController < ApplicationController
  def index
  	 @cities = City.all
	   
  end

  def new
  end

  def create
    @w = WeatherService.get(params[:name])

     if @w
      @temperature = (9.0/5) * (@w[:temperature] - 273)+ 32

      city = City.new(
          name: params[:name],
          landmark: params[:landmark], 
          population: params[:population], 
          weather: @temperature, 
        )

      city.save
    end
  end

  def update
    # @cities = City.all
    # if @cities.key?(params[:name])
    #    @thiscity = @cities[params[:name]]
  

    #   @thiscity.update(
    #       #name: params[:name],
    #       landmark: params[:landmark], 
    #       population: params[:population], 
    #       #weather: @temperature, 
    #     )
    # end
  end

  def post_up
    @cities = City.all
    if @cities.key?((params[:name]).to_sym)
       @thiscity = @cities[(params[:name]).to_sym]
  

      @thiscity.update(
          #name: params[:name],
          landmark: params[:landmark], 
          population: params[:population], 
          #weather: @temperature, 
        )
    end
    redirect_to "/cities/"
  end

end

app/controllers/main_controller.rb
require_relative '../services/weather_service'

class MainController < ApplicationController

  def index
    # Uncomment and pass a parameter to the get function
    @w = WeatherService.get(params[:city])

    if @w
    	@temperature = (9.0/5) * (@w[:temperature] - 273)+ 32

    	city = City.new(
    		name: params[:city],
    		temperature: @temperature, 
    		description: @w[:description]
    	)

    	city.save
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<!-- Your code here -->
<html><!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>


	<% @cities.each do |city| %>
	<!-- In between these two ruby tags, put your code for displaying a city! -->
	<% if not city.nil? %>
		<p> <%= city[1].name %> </p>
		<p> <%= city[1].weather %></p>
		<p> <%= city[1].population %></p>
	<% else %>
	
 
	<% end %>

	<% end %>

<%= link_to "Create new city", new_city_path %>



</body>
</html>

app/views/cities/new.html.erb
<%= form_with method: "post", url: cities_path do |form| %>
 <p>City</p> <%= form.text_field :name %>
 <p>population</p> <%= form.text_field :population %>
  <p>landmark</p><%= form.text_field :landmark %>
  <%= form.submit %>
<% end %>

app/views/cities/update.html.erb
<%= form_with method: "post", url: "/cities/update" do |form| %>
 <p>City</p> <%= form.text_field :name %>
 <p>population</p> <%= form.text_field :population %>
  <p>landmark</p><%= form.text_field :landmark %>
  <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails DeCal Lab and HW 3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<!-- Your code here -->
<html><!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
Hello, <%= @name%>!



<% if not @w.nil? %>
	<h1><%= @w[:city] %></h1>
	<p>
		It's <%= @temp%>°F
		and it looks like <%= @w[:description] %>
	</p>
<% end %>

<%= form_with local: true, method: "get" do |form| %>
  <%= form.text_field :city %>

  <%= form.submit %>
<% end %>

<% City.all.each do |c| %>
<% if not c.nil? %>
	<h1> <%= c.name %></h1>
	<p>
		It's <%= c.temperature %>°F
		and it looks like <%= c.description %>
	</p>
<% end %>
<% end %>
</body>
</html>